# ----------------------------
# CONFIGURE Broker CACHE USING REDIS.

# Configure the Broker with Redis
redis.broker.hostname=localhost

# Choose the port your Redis instance exposes (Docker run below publishes 45000 -> 6379)
redis.broker.port=45000

# Logging level (optional)
logging.level.edu.eci.arsw.psredis=INFO
